import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import fs from 'fs';

const categories = fs
  .readdirSync('docs', { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((dir) => ({
    label: dir.name.charAt(0).toUpperCase() + dir.name.slice(1),
    dirName: dir.name,
  }));

const sidebars: SidebarsConfig = {};

categories.forEach((category) => {
  sidebars[category.dirName] = [
    {
      type: 'category',
      label: category.label,
      link: {
        type: 'doc',
        id: `${category.dirName}/index`,
      },
      collapsible: false,
      items: [
        {
          type: 'autogenerated',
          dirName: category.dirName,
        },
      ],
    },
  ];
});

export default sidebars;
