import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const categories = [
  { label: 'Drinks', dirName: 'drinks' },
  { label: 'Tunes', dirName: 'tunes' },
  { label: 'Dives', dirName: 'dives' },
];

const sidebars: SidebarsConfig = {};

categories.forEach((category) => {
  sidebars[category.dirName] = [
    {
      type: 'category',
      label: category.label,
      link: {
        type: 'doc',
        id: `${category.dirName}/index`,
      },
      items: [
        {
          type: 'autogenerated',
          dirName: category.dirName,
        },
      ],
    },
  ];
});

export default sidebars;
