name: Docusaurus

on:
  schedule:
    - cron: 0 0 * * 0

  push:
    branches:
      - main
    paths:
      - .github/workflows/docusaurus.yml
      - docusaurus/**
      - "!**.gitignore"

  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/docusaurus.yml
      - docusaurus/**
      - "!**.gitignore"

  workflow_dispatch:

defaults:
  run:
    working-directory: docusaurus

env:
  WORK_DIR: docusaurus

jobs:
  build:
    name: Build
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Check out repository (drinks)
        uses: actions/checkout@v7
        with:
          repository: mattiasholm/drinks
          path: drinks

      - name: Check out repository (dives)
        uses: actions/checkout@v7
        with:
          repository: mattiasholm/dives
          path: dives

      - name: Copy files (drinks)
        run: cp drinks/drinks/*.md docusaurus/docs/drinks && cp drinks/syrups.json docusaurus/static/drinks/syrups.json
        working-directory: .

      - name: Copy files (dives)
        run: cp dives/dives.csv docusaurus/static/dives.csv && cp dives/certs.json docusaurus/static/dives/certs.json
        working-directory: .

      - name: Cache node modules
        uses: actions/cache@v6
        with:
          path: ${{ env.WORK_DIR }}/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}/package-lock.json', env.WORK_DIR)) }}

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.WORK_DIR }}/build

  release:
    name: Release
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: ${{ steps.deploy.outputs.page_url }}
    permissions:
      id-token: write
      pages: write
    steps:
      - name: Deploy site
        id: deploy
        uses: actions/deploy-pages@v5
